### ISSUE TITLE
Unable to complete application test, cannot connect to Sonarr. Name does not resolve (vpn:8989)

### ISSUE THREAD

**Issue by bpahunt** [AdrienPoupa/docker-compose-nas#37]
Due to my location I have to put Prowlarr behind the VPN in order to add indexers successfully. This works fine and I have adjusted the widget URL to account for this.

All works well but this then breaks the app in Sonarr and Radarr. Makes sense as the Prowlarr URL has changed from http://prowlarr:9696/prowlarr to http://vpn:9696/prowlarr.

Updating the Prowlarr URL does not fix the issue. Working on the assumption that therefore Sonarr and Radarr should also sit behind the VPN but updating their respective URL's still returns the same error.

![image](https://github.com/AdrienPoupa/docker-compose-nas/assets/149238821/f3b4ba5f-36d4-4c97-a3cc-fd3193d03777)

I revert everything back pre-VPN and everything seems to then work fine but indexers are broken.

**Comment by AdrienPoupa** [comment]
Hi there, have you added `network_mode: "service:vpn"` to all the applications that should go through the VPN?

**Comment by bpahunt** [comment]
Yes, that's right. Have tried just adding prowlarr. With that failing I tried adding to both sonarr and radarr.

**Comment by AdrienPoupa** [comment]
You should only need to add the service line to the Prowlarr service and only update the Prowlarr URL in Radarr and Sonarr. Also restart the whole stack when done.

I'll try to see if something else is missing.

**Comment by AdrienPoupa** [comment]
Coming back to this, I was able to make it working. To make Prowlarr and Radarr see each other, both need to be using the VPN indeed, so the following block must be added to Prowlarr, Radarr and any other *arr apps as needed:

```yml
    network_mode: "service:vpn"
    depends_on:
      vpn:
        condition: service_healthy
```

Then in Prowlarr, use `localhost` rather than `vpn` as the hostname, since they're on the same network now:

![image](https://github.com/AdrienPoupa/docker-compose-nas/assets/15086425/5172a665-c19a-47f5-a97d-8e1d0f038f8c)

I'd also adjust the healthcheck to mark all the containers using the VPN as unhealthy if the container reboots or changes server: `test: [ "CMD", "curl", "--fail", "http://127.0.0.1:7878/radarr/ping", "https://google.com" ]`

Hope that helps!

**Comment by bpahunt** [comment]
Many thanks, very helpful indeed!
