### ISSUE TITLE
qBittorrent 4.6.1 password issue

### ISSUE THREAD

**Issue by wrapper** [AdrienPoupa/docker-compose-nas#40]
Due to a bug in 4.6.1 the default password doesn't work and it won't generate a temp password either. Details here: https://www.reddit.com/r/unRAID/comments/180ou0b/psa_if_you_cant_login_to_qbittorrent_pass/

I haven't found a solution as manually adding a password to the conf gets erased when restarting the container

**Comment by AdrienPoupa** [comment]
I saw people forcing 4.6.0, setting the password and then upgrading to 4.6.1. The whole situation is kinda messy for Docker-based installation: https://github.com/linuxserver/docker-qbittorrent/issues/268

I think qbittorrent fixed it and 4.6.2 should be working better.

I was not affected since I disabled authentication on localhost, but I guess you need to login first to enable this.

**Comment by wrapper** [comment]
Thanks. Temp solution for me was to change the image to `lscr.io/linuxserver/qbittorrent:4.6.0`
