### ISSUE TITLE
Continously pinging google.com?

### ISSUE THREAD

**Issue by wrapper** [AdrienPoupa/docker-compose-nas#44]
My pihole is showing that my nas is pinging google.com every few seconds. It is running tailscale and traefik (also syncthing)

Any idea why it would be doing this so frequently? Not sure which logs to look at.

Thanks

**Comment by AdrienPoupa** [comment]
This is qBittorrent and the VPN checking they're still online, otherwise they should reboot: 

- https://github.com/AdrienPoupa/docker-compose-nas/blob/master/docker-compose.yml#L244
- https://github.com/AdrienPoupa/docker-compose-nas/blob/master/docker-compose.yml#L298

It's "normal", but we could use a different website to check for connectivity; I was not sure which URL to ping for this to be honest. It could be also set as a configuration.

**Comment by wrapper** [comment]
Ah okay, as I'm using a system wide VPN I will remove that line. Either way, every 30s is probably too much?

Thanks

**Comment by AdrienPoupa** [comment]
It's always a balance between pinging too much and letting the service go down for too long, usually healthchecks will ping every few seconds, feel free to lower this in your setup :)
