### ISSUE TITLE
File structure and hardlinks

### ISSUE THREAD

**Issue by kphilippart** [AdrienPoupa/docker-compose-nas#46]
Hi,
Thank you for your great work !

I can't figure out how hardlinks work.
I have the same file structure as you:

```
data
├── torrents
│  ├── movies
│  └── tv
└── media
   ├── movies
   └── tv
```

qBittorent downloads files in /data/torrents. /data/torrents/movies and /data/torrents/tv both stay empty. 
My files permissions for all files and directories inside data: `drwxrwxr-x xxx xxx`

If go inside a container using this cmd: `docker exec -ti sonarr bash`  my files permission has a different user and grp:
`drwxrwxr-x abc abc` . Is it normal ?

the "create hardlink" in both Radarr and Sonarr configuration are ticked

Even though everything seems correctly configured, files from /data/torrents are not automatically linked to /data/media. What did I miss ? 

Thanks in advance for your help.

**Comment by AdrienPoupa** [comment]
Hi there, my pleasure!

> qBittorent downloads files in /data/torrents. /data/torrents/movies and /data/torrents/tv both stay empty.

Sounds like Radarr and Sonarr do not apply the right tags. Is the category set in Client Settings?

![image](https://github.com/AdrienPoupa/docker-compose-nas/assets/15086425/11257158-793f-4abc-8375-b086fb6653c5)

> If go inside a container using this cmd: docker exec -ti sonarr bash my files permission has a different user and grp:
drwxrwxr-x abc abc . Is it normal ?

Yes, `abc` is the default user mapped to ID 1000 in all LinuxServer Docker images.

I am not sure what could be wrong, is the Root folder set to `/data/media/tv` in Sonarr's media management settings, and `/data/media/movies` for Radarr? I am assuming `Use Hardlinks instead of Copy` is enabled.

**Comment by kphilippart** [comment]
The category was "tv-sonarr" in sonarr and "radarr" in radarr,I changed it to "tv" like in your screen and "movies" for Sonar.

I don't have any indexers configured in sonarr and radarr, I thought Prowlarr was used to download files. Here, the default category is "prowlarr". Do I need to change it ?

`Use Hardlinks instead of Copy ` is enabled

**Comment by kphilippart** [comment]
Ok, I was starting the download from Prowlarr and not from radarr, therefore, no links were created.

I've added a movie from radarr and after that, the file was correctly hardlinked from `/data/torrents` to `/data/media/movies`. However, the `/data/torrents/movies` is not used, qBittorent downloads files in his default save path `/data/torrents`. How could I make it store files in the correct subdfolder (movies or tv) ?

**Comment by AdrienPoupa** [comment]
This is odd, is your qBittorrent similar to this?

![image](https://github.com/AdrienPoupa/docker-compose-nas/assets/15086425/d4799bb1-fde4-4bf5-8f6f-3d96dbefcf68)
