### ISSUE TITLE
How does this compare to Saltbox (aka Cloudbox)?

### ISSUE THREAD

**Issue by Sire** [AdrienPoupa/docker-compose-nas#53]
Newbie question, has anyone tried [Saltbox](https://github.com/saltyorg/Saltbox) (was previously called Cloudbox) and can compare these two? They both seem equally popular and quite similar.

**Comment by AdrienPoupa** [comment]
Hi there! While the goal of both our projects is very similar, the technical strategies to achieve it differ wildly.

Saltbox makes heavy use of [Ansible](https://www.ansible.com/) and seems to use it to generate a Docker compose file on demand. It also uses [a subdomain per application](https://docs.saltbox.dev/saltbox/basics/accessing_apps/). There's more applications available to choose from (Plex, Tautulli, and many others).

On the other hand, Docker Compose NAS is a "simple" Docker-Compose file that can be run directly with a `docker compose up -d` without needing external dependencies such as Ansible. It is configurable but more opinionated about which applications are available and how they are setup (using subfolders when it is possible for example).

I'm obviously biased, but I see Docker-Compose NAS as a simpler project given everything is explicitly declared in the Compose file and there is no templating/Ansible automation going on. However it has fewer applications available so that may be a limiting point.

I hope that answers your question!

**Comment by Sire** [comment]
Thanks for the detailed comparison!
